openapi: 3.0.3
info:
  title: Sunglasses.io
  version: 1.0.11
  description: " Our online Sunglass Store application features a backend server and API to allow users to shop from existing ineventory."
  termsOfService: https://github.com/nsLittle/sunglasses-io
  contact:
    email: notsolittle88@gmail.com
    name: Mutsumi Hata
    url: https://github.com/nsLittle
servers:
  - url: http://localhost:3000
    variables: {}
  - url: http://localhost:3000
    variables: {}
    description: Local Host
paths:
  /:
    summary: Home Page
    description: Home Page with WireFrame
    get:
      summary: GET home page
      description: GET home page with wireframe
      operationId: get.home
      responses:
        default:
          description: Default error sample response
  /brands:
    summary: Brands
    description: Name of all brands
    get:
      summary: GET brands
      description: GET name of all brands
      operationId: get.brands
      responses:
        default:
          description: Default error sample response
  /brands/:name:
    summary: Sunglasses by brand
    description: Product details of sunglasses by brands
    get:
      summary: GET product details
      description: GET product details of sunglasses by product brand
      operationId: get.brand.:name
      responses:
        default:
          description: Default error sample response
  /products:
    summary: Sunglases
    description: Name of all sunglasses
    get:
      summary: GET sunglasses
      description: GET name of all sunglasses
      operationId: get.products
      responses:
        default:
          description: Default error sample response
  /products/:name:
    summary: Product details
    description: Product details of specific sunglasses
    get:
      summary: GET product details
      description: GET product details of sunglsses by product name
      operationId: get.products.:name
      responses:
        default:
          description: Default error sample response
  /users:
    summary: Users
    description: Name of all users
    get:
      summary: GET users
      description: GET. users
      operationId: get.users
      responses:
        default:
          description: Default error sample response
